version: "2"

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - unparam
    - gocritic
    - revive
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    govet:
      enable-all: true
    misspell:
      locale: US

formatters:
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes: github.com/ntancardoso/dbc

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
